name: 'direnv action'
description: 'Provides environment variables via direnv'
branding:
  icon: play
  color: green
inputs:
  masks:
    description: 'Comma-separated list of environment variable names to mask'
    required: true
    default: ''
  direnvVersion:
    description: 'direnv version to use'
    required: true
    default: '2.37.1'
  path:
    description: 'Directory where direnv is evaluated'
    required: true
    default: .
runs:
  using: 'node24'
  main: 'dist/index.js'
