name: 'direnv action'
description: 'Privides environment variables via direnv'
branding:
  icon: play
  color: green
inputs:
  masks:
    description: 'Comma seprated list of environment variables to mask'
    required: true
    default: ''
  direnvVersion:
    description: 'direnv version to use'
    required: true
    default: '2.32.1'
  path:
    description: "directory for direnv to use"
    required: true
    default: .
runs:
  using: 'node20'
  main: 'dist/index.js'
