name: "check-dirty"
on:
  pull_request:
    branches:
      - v1

jobs:
  check-dirty:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: 20
    - run: npm ci
    - run: npm run prepare
    - run: |
        git diff --stat --exit-code
