name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: 24
    - run: npm ci
    - run: npm test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: 24
    - run: npm ci
    - run: npm run prepare
    - uses: ./
      with:
        masks: SECRET1, SECRET2
        required: DIRENV_ACTION_TEST
        direnvVersion: 2.32.3
        direnvChecksum: sha256:c0443e4600e4b93ec253e663fff18b5fb490cc555b1fc72f0ab22beaa2bb9810
    - run: printenv | grep DIRENV_ACTION_TEST
    - run: echo $PATH | grep $(pwd)/bin
    - run: printenv

  test-default-option:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: 24
    - run: npm ci
    - run: npm run prepare
    - uses: ./
    - run: printenv | grep DIRENV_ACTION_TEST
    - run: echo $PATH | grep $(pwd)/bin
    - run: printenv
